# Generated by Django 5.2.1 on 2026-07-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=300, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachilar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('profession', models.CharField(max_length=200, verbose_name='Kasbi')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/', verbose_name='Rasm')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(verbose_name='Qisqa tavsif')),
                ('full_description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('image', models.ImageField(blank=True, upload_to='courses/', verbose_name='Rasm')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Narxi (so'm)")),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Davomiyligi')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name='Darslar soni')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='Kategoriya')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Dars nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('content', models.TextField(blank=True, verbose_name='Dars matni')),
                ('video_url', models.URLField(blank=True, verbose_name='Video havolasi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
    ]
