# Generated by Django 5.2.1 on 2026-07-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="To'liq ismi")),
                ('photo', models.ImageField(blank=True, upload_to='students/', verbose_name='Rasm')),
                ('profession', models.CharField(max_length=200, verbose_name='Hozirgi kasbi')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Ish joyi')),
                ('quote', models.TextField(blank=True, verbose_name="O'z so'zi")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Oltin'), (2, '2 - Kumush'), (3, '3 - Bronza')], default=3, verbose_name='Reyting')),
                ('is_top', models.BooleanField(default=False, verbose_name="Top o'quvchi")),
                ('graduated_year', models.PositiveIntegerField(default=2025, verbose_name='Bitirgan yili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.course', verbose_name='Bitirgan kurs')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['rating', '-graduated_year'],
            },
        ),
    ]
